---
on:
  push:
    tags:
      - '*'

name: Publish tagged image to Docker Hub

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: robsontenorio/meilisearch
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag_names: true
