---
on:
  push:
    tags:
      - '*'

name: Publish tagged image to Docker Hub

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:        
          # list of Docker images to use as base name for tags
          images: |
            robsontenorio/meilisearch
          # generate Docker tags based on the following events/attributes
          tags: |
            type=semver,pattern={{version}}            
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
      - name: Publish to Registry
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          platforms: linux/amd64,linux/arm64/v7,linux/arm64/v8
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
